name: Fuel Scraper

on:
  workflow_dispatch:

  schedule:
    - cron: "30 1 * * *"

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scraper/requirements.txt

      - name: Run Fuel Scraper
        run: |
          python scraper/fuel_scraper.py

      - name: Run LPG Scraper
        run: |
          python scraper/lpg_scraper.py

      - name: Run Gold & Silver Scraper
        run: |
          python scraper/gold_silver_scraper.py

      - name: Run Weather Scraper
        run: |
          python scraper/weather_scraper.py

      - name: Upload Goa HTML
        uses: actions/upload-artifact@v4
        with:
          name: goa-html
          path: goa.html

      - name: Upload LPG HTML
        uses: actions/upload-artifact@v4
        with:
          name: lpg-html
          path: lpg.html

      - name: Commit Updated Data
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions@users.noreply.github.com"

          git add data/*.json

          git diff --cached --quiet || git commit -m "Update Fuel, LPG, Gold, Silver & Weather"

          git push
